#SERVER
server:
  port: 21200
  address: 127.0.0.1

#JPA/MYSQL
spring:
  flyway:
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

#AUTH
app:
  auth:
    jwtSecret: secretKey
    jwtExpirationMs: 604800000